
- name: set interface name as fact
  set_fact:
    current_interface: "{{ interface.name }}"

- name: "destroy/bridge.yml - generate dnsmasq instance for {{ current_interface }}"
  file:
    state: absent
    dest: "/etc/dnsmasq.d/{{ current_interface }}.conf"
  notify:
    - stop and disable dnsmasq interface service

- name: "destroy/bridge.yml - generate interface file for {{ interface.name }}"
  file:
    state: absent
    dest: "/etc/network/interfaces.d/{{ interface.name }}"
  notify:
    - down interface
    - remove interface
    - restart networking

- meta: flush_handlers
