
- name: destroy/proxy.yml - remove dnsmasq instance for proxy
  file:
    state: absent
    path: /etc/dnsmasq.d/proxy.conf
  notify:
    - stop and disable dnsmasq proxy service

- meta: flush_handlers
